### ISSUE TITLE
Too many requests for metrics will lead to missing data

### ISSUE THREAD

**Issue by nvtkaszpir** [akpw/mktxp#110]
- spawned image with mktxp v1.2.2 in k8s pod on port 49090
- prometheus ServiceMonitor scrapes it well
- added liveness/readiness probes and suddenly some requests for metrics are truncated (they respond fast but are truncated)

After few refreshes it returns full processed data but disappears again.
Metrics output is trimmed after process_max_fds line.

This effectively makes Prometheus to not have metrics at all.

removing probes fixes the issue.

I thought that PYTHONUNBUFFERED might help but it does not.

Example commented code below:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mktxp
  labels:
    app.kubernetes.io/name: mktxp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mktxp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: mktxp
    spec:
      volumes:
        - name: devices
          secret:
            secretName: mktxp
            defaultMode: 420
        - name: mktxp
          configMap:
            name: mktxp
            defaultMode: 420
      containers:
        - name: mktxp
          env:
            - name: PYTHONUNBUFFERED
              value: "True"
          image: ghcr.io/akpw/mktxp:latest
          ports:
            - name: http
              containerPort: 49090
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 32Mi
          volumeMounts:
            - name: devices
              readOnly: true
              mountPath: /home/mktxp/mktxp/mktxp.conf
              subPath: mktxp.conf
            - name: mktxp
              readOnly: true
              mountPath: /home/mktxp/mktxp/_mktxp.conf
              subPath: _mktxp.conf
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 49090
          #     scheme: HTTP
          #   timeoutSeconds: 10
          #   periodSeconds: 15
          #   successThreshold: 1
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 49090
          #     scheme: HTTP
          #   timeoutSeconds: 10
          #   periodSeconds: 15
          #   successThreshold: 1
          #   failureThreshold: 3
          # startupProbe:
          #   httpGet:
          #     path: /
          #     port: 49090
          #     scheme: HTTP
          #   timeoutSeconds: 10
          #   periodSeconds: 15
          #   successThreshold: 1
          #   failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      dnsPolicy: ClusterFirst
      automountServiceAccountToken: false
      securityContext: {}
      schedulerName: default-scheduler
      enableServiceLinks: false
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```

**Comment by akpw** [comment]
can you check with the latest?

**Comment by Moleus** [comment]
I had the same problem with readiness/liveness probes enabled and prometheus scrapes. I had no metrics in grafana and decided to investigates whats wrong. I've forwarded port from service and sent a few requests from browser (screenshot below), as you can see the first response contained all metrics but the second ends with `process_max_fds` line. After disabling probes everything works great.

- image version: ghcr.io/akpw/mktxp:stable-20240423085520

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mktxp
  namespace: "{{ mktxp_namespace }}"
  labels:
    app: mktxp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mktxp
  template:
    metadata:
      labels:
        app: mktxp
    spec:
      containers:
        - name: mktxp
          image: "{{ mktxp_image_name }}:{{ mktxp_image_tag }}"
          imagePullPolicy: IfNotPresent
          args:
            - --cfg-dir
            - /mktxp_config
            - export
          ports:
            - containerPort: 49090
              name: http
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /metrics
              port: 49090
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            httpGet:
              path: /metrics
              port: 49090
              scheme: HTTP
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: mktxp-credentials
              mountPath: /mktxp_config
      volumes:
        - name: mktxp-credentials
          secret:
            secretName: mktxp-credentials
```

![image](https://github.com/akpw/mktxp/assets/66182149/15eb1a99-b82a-4b28-9ee6-9b42618f0a1c)
